### PR TITLE
Allow disabling the preview

### PR DESCRIPTION
**Pull request by graywolf336**
For my usage, I need to disable the file preview. As far as I can tell, this is the only part required. I am highly open to suggestions and advice on how to better implement this.

### CODE REVIEW

**Comment by jarekwg** [comment]
What about setting `detailRenderer` prop to `null`, and having code skip mounting that component in this case.

**Comment by graywolf336** [comment]
Ha, that works even better. Thanks!

**Comment by graywolf336** [comment]
Screen Shot 2020-02-03 at 9 28 04 AM

Although we run into this issue then.

**Comment by jarekwg** [comment]
Nah I meant we still need a PR for it, such that if RKFB sees `null` as the provided detailRenderer, it'll just not render anything.
An alternative that you can do entirely on your end is to write your own detailRenderer component that renders nothing.

**Comment by graywolf336** [comment]
Ah okay, I misunderstood what you said. I ended up going the route of my own detail renderer that rendered nothing. I'll see about creating a pull request if I can get some time.

**Pull request closed without merging**
