### PR TITLE
add files to browserProps

### PR DESCRIPTION
**Pull request by cat-bro**
Add file information to the props that so that it can be accessed by other renderers.

### CODE REVIEW

**Comment by jarekwg** [comment]
Can you give some more info on the use case? Browserprops shouldn't have access to the files themselves; only the renderers and their props. The files are handed to the renderers later in the pipeline iirc.

**Comment by cat-bro** [comment]
I'm rendering a header for each browser on the logbook page.  I can supply props to it and it also has access to the browser props.  The PBI asks for the number of photos above each browser.  All I need is the number but being able to check for nested content would potentially be useful (through file names)

**Comment by cat-bro** [comment]
The first file attached to this https://uptickhq.atlassian.net/browse/WOR-691 is what I'm trying to get to

**Comment by jarekwg** [comment]
Hrm okay I see.
So FileRender is only fed in the individual file it needs to know about whilst HeaderRenderer is fed nothing.
For this use case we want HeaderRenderer to be able to see all of the files so that it can summarise them (with a count).
So instead of exposing `files` to all renderers, could we just pass the files to where we mount the HeaderRenderer? ie. to `headerProps`maybe?

_Furthermore_, we also need to ask:
- Do we need to dynamically change the count as results are filtered?
- Should we pass only the files relevant to the given header, rather than all of them (in the case of nested grouping)?
- Can/should we pass the count only, rather than the actual list of files?
I had a brief chat with @scaredcat about this and we're both thinking that passing the count alone is sufficient.. do you think there may be countercases where more should be passed?

**Comment by cat-bro** [comment]
The count alone will do.

**Comment by cat-bro** [comment]
The use case I'm dealing with is a folder with no subfolders, no filtering, no ability to create or delete.  

Another possibility would be having a callback in the wrapper that could bring back info on the files

**Comment by jarekwg** [comment]
Yeah i was toying with idea of callback too. Not opposed to this approach either. Just don't think we'd want to pass the full list of files into the callback, which then leads to us having to decide what we _do_ pass in.

**Comment by jarekwg** [comment]
Remind me to publish tomorrow.

**Comment by cat-bro** [comment]
@jarekwg reminder - please publish and let me know, I can bump the version in customerportal

**Comment by jarekwg** [comment]
@cat-bro done! 1.3.2

**Pull request merged**
